"""Render RESULTS.md from the results DB.

Usage: python -m pipeline.report_md [--run-date YYYY-MM-DD] [--out PATH]
"""

import argparse
import sys

from pipeline.build_leaderboard import compute_scores
from pipeline.config import RESULTS_MD_PATH
from pipeline.data_io import connect
from pipeline.scorer import rank_models


def render(conn, run_date):
    scores = compute_scores(conn)
    ranking = rank_models(scores)
    (total,) = conn.execute("SELECT COUNT(*) FROM results").fetchone()
    lines = [
        f"# Ticket-Triage Benchmark -- Monthly Results ({run_date})",
        "",
        f"Rows scored: {total} across {len(scores)} models.",
        "Scoring per docs/SPEC.md (weighted per-category F1).",
        "",
        "| Rank | Model | Overall |",
        "|------|-------|---------|",
    ]
    for i, model in enumerate(ranking, 1):
        lines.append(f"| {i} | {model} | {scores[model]:.4f} |")
    lines += ["", "_Generated by pipeline/report_md.py._", ""]
    return "\n".join(lines)


def main(argv=None):
    ap = argparse.ArgumentParser()
    ap.add_argument("--run-date", default="2026-08-12")
    ap.add_argument("--out", default=str(RESULTS_MD_PATH))
    args = ap.parse_args(argv)
    conn = connect()
    text = render(conn, args.run_date)
    with open(args.out, "w", encoding="utf-8") as f:
        f.write(text)
    conn.close()
    print(f"wrote {args.out}")


if __name__ == "__main__":
    sys.exit(main())
